---
# - name: Determine content views
#   command: "hammer {{ foreman_connect_string }} content-view list --organization \"{{ foreman_organization }}\""
#   changed_when: false
#   register: r
#   tags: cv
# - debug:
#     var: r
#     verbosity: 2
#   tags: cv
# - name: Parse content views
#   set_fact:
#     content_views: "{{ r.stdout | from_json }}"
#   tags: cv
# - debug:
#     var: content_views
#     verbosity: 2
#   tags: cv
# - name: Map repos
#   include_tasks: map_repos.yml
#   loop: "{{ content_views }}"
#   loop_control:
#     loop_var: cv
#   tags: cv

- name: Determine content views
  foreman_search_facts:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_verify_ssl }}"
    resource: content_views
    # search: organization_id=1
  register: r
  delegate_to: localhost
- debug:
    var: r
    verbosity: 2
- set_fact:
    content_views: "{{ r.resources }}"
- debug:
    var: content_views
    verbosity: 2 
- name: Map repos
  include_tasks: map_repos.yml
  loop: "{{ content_views }}"
  loop_control:
    loop_var: cv

# - fail:
#   when: true