---
- name: Determine domains
  foreman_search_facts:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_verify_ssl }}"
    resource: domains
    search: organization={{foreman_organization}}
  register: r
  delegate_to: localhost
- set_fact:
    domains: "{{ r.resources }}"
- debug:
    var: domains
    verbosity: 2

# - fail:
#   when: true

# Use hammer as foreman_search_facts still does not retain location association
- name: Extract domain info
  command: "hammer {{ foreman_connect_string }} domain info --id {{ item.id }} --organization \"{{ foreman_organization }}\""
  changed_when: false
  register: r
  loop: "{{ domains }}"
- set_fact:
    domain_info: "{{ r.results | json_query('[*].stdout') | map('from_json') | list }}"
- debug:
    var: domain_info
    verbosity: 2
    
- name: Create domains
  template:
    src: "templates/create-domains.yml.j2"
    dest: "{{ output_dir }}/create-domains.yml"