---
- name: Determine lifecycle environments
  command: "hammer {{ foreman_connect_string }} lifecycle-environment list --organization \"{{ foreman_organization }}\""
  changed_when: false
  register: r
- debug:
    var: r
    verbosity: 2
- name: Parse lifecycle environments
  set_fact:
    lifecycle_environments: "{{ r.stdout | from_json }}"
- debug:
    var: lifecycle_environments
    verbosity: 2
- name: Create lifecycle environments
  template:
    src: "templates/create-lifecycle-environments.yml.j2"
    dest: "{{ output_dir }}/create-lifecycle-environments.yml"
- template:
    src: "templates/create-lifecycle-environment.yml.j2"
    dest: "{{ output_dir }}/create-lifecycle-environment.yml"
