---

- name: Determine lifecycle environments
  foreman_search_facts:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_verify_ssl }}"
    resource: lifecycle_environments
    search: organization_id=1
  register: r
  delegate_to: localhost
- set_fact:
    lifecycle_environments: "{{ r.resources }}"
- debug:
    var: lifecycle_environments
    verbosity: 1
- template:
    src: "templates/create-lifecycle-environment.yml.j2"
    dest: "{{ output_dir }}/create-lifecycle-environment.yml"
- template:
    src: "templates/create-lifecycle-environments.yml.j2"
    dest: "{{ output_dir }}/create-lifecycle-environments.yml"

- fail:
  when: true