---
- name: Determine location
  foreman_search_facts:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_verify_ssl }}"
    resource: locations
    # search: organization={{foreman_organization}}
  register: r
  delegate_to: localhost
- debug:
    var: r
    verbosity: 2
- set_fact:
    locations: "{{ r.resources }}"
- debug:
    var: locations
    verbosity: 2

- name: Create locations
  template:
    src: "templates/create-locations.yml.j2"
    dest: "{{ output_dir }}/create-locations.yml"
