---
# - name: Determine partition tables
#   command: "hammer {{ foreman_connect_string }} partition-table list --organization \"{{ foreman_organization }}\""
#   changed_when: false
#   register: partition_tables
# - debug:
#     var: partition_tables
#     verbosity: 2

- name: Determine Partition Tables
  foreman_search_facts:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_verify_ssl }}"
    resource: ptables
    # search: organization={{foreman_organization}}
  register: r
  delegate_to: localhost
- debug:
    var: r
    verbosity: 2
- set_fact:
    ptables: "{{ r.resources }}"
- debug:
    var: ptables
    verbosity: 2

# - name: Create locations
#   template:
#     src: "templates/create-ptables.yml.j2"
#     dest: "{{ output_dir }}/create-ptables.yml"

# - fail:
#     when: true