---
- name: Determine subnets
  foreman_search_facts:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_verify_ssl }}"
    resource: subnets
    search: organization={{foreman_organization}}
  register: r
  delegate_to: localhost
- set_fact:
    subnets: "{{ r.resources }}"
- debug:
    var: subnets
    verbosity: 2

# - fail:
#   when: true

# We still have to do this with hammer as foreman_search_facts does not return domain or location association  
- name: Extract subnet info
  command: "hammer {{ foreman_connect_string}} subnet info --id {{ item.id }} --organization \"{{ foreman_organization }}\""
  changed_when: false
  register: r
  loop: "{{ subnets }}"
- set_fact:
    subnet_info: "{{ r.results | json_query('[*].stdout') | map('from_json') | list }}"
- debug:
    var: subnet_info
    verbosity: 2

# - fail:
#   when: true

- name: Create subnets
  template:
    src: "templates/create-subnets.yml.j2"
    dest: "{{ output_dir }}/create-subnets.yml"